CREATE TABLE IF NOT EXISTS lesson_plans (
    id INT AUTO_INCREMENT PRIMARY KEY,
    teacher_id INT NOT NULL,
    staff_id VARCHAR(30),
    subject_id INT NOT NULL,
    class_id INT NOT NULL,
    term_id INT NOT NULL,
    academic_session_id INT,
    week_no INT,
    date_planned DATE,
    duration VARCHAR(100),
    topic VARCHAR(255) NOT NULL,
    sub_topic VARCHAR(255),
    learning_objectives TEXT,
    previous_knowledge TEXT,
    instructional_materials TEXT,
    teaching_methods TEXT,
    introduction TEXT,
    presentation_steps TEXT,
    classroom_activities TEXT,
    student_activities TEXT,
    assessment TEXT,
    assignment TEXT,
    reference_materials TEXT,
    remarks TEXT,
    status ENUM('draft','submitted','under_review','approved','rejected') DEFAULT 'draft',
    completion_percentage INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (teacher_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE CASCADE,
    FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE CASCADE,
    FOREIGN KEY (term_id) REFERENCES terms(id) ON DELETE CASCADE,
    FOREIGN KEY (academic_session_id) REFERENCES academic_sessions(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS lesson_plan_reviews (
    id INT AUTO_INCREMENT PRIMARY KEY,
    lesson_plan_id INT NOT NULL,
    reviewer_id INT NOT NULL,
    status ENUM('under_review','approved','rejected','correction_requested') NOT NULL,
    comment TEXT,
    reviewed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (lesson_plan_id) REFERENCES lesson_plans(id) ON DELETE CASCADE,
    FOREIGN KEY (reviewer_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
